# Generated by Django 3.2.9 on 2021-12-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='refrence_id',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
