# Generated by Django 3.2.9 on 2021-12-14 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Waterbill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100)),
                ('ammount', models.PositiveIntegerField()),
                ('transaction_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('processing', 'PROCESSING'), ('success', 'SUCCESS'), ('pending', 'PENDING'), ('failed', 'FAILED')], max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('paid_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Phonebill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100)),
                ('ammount', models.PositiveIntegerField()),
                ('transaction_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('processing', 'PROCESSING'), ('success', 'SUCCESS'), ('pending', 'PENDING'), ('failed', 'FAILED')], max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Internetbill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100)),
                ('ammount', models.PositiveIntegerField()),
                ('transaction_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('processing', 'PROCESSING'), ('success', 'SUCCESS'), ('pending', 'PENDING'), ('failed', 'FAILED')], max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Electricitybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100)),
                ('ammount', models.PositiveIntegerField()),
                ('transaction_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('processing', 'PROCESSING'), ('success', 'SUCCESS'), ('pending', 'PENDING'), ('failed', 'FAILED')], max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
